import React,{useEffect,useState} from 'react';
import {ApiClient} from '../../lib/api';
import {Destination,TourismStats} from '../../types';
import {Empty,Notice,PageHeading} from '../../components/Workspace';
const metrics:[string,keyof TourismStats][]=[['Total aktivitas','totalPlatformActivities'],['Titik dijelajahi','totalExplorePointsDiscovered'],['Kuis selesai','totalQuizzesCompleted'],['Event diikuti','totalEventParticipations'],['Reward ditukar','totalRewardRedemptions'],['Usaha lokal dikunjungi','totalLocalDiscoveryVisits']];
export function GovernmentDashboard({onNavigate:unused}:{onNavigate:(p:string)=>void}) {
 const [stats,setStats]=useState<TourismStats|null>(null),[performance,setPerformance]=useState<{destination:Destination;stats:TourismStats}[]>([]),[insights,setInsights]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[downloaded,setDownloaded]=useState(false);
 const load=async()=>{setLoading(true);setError('');const [dashboard,destinations]=await Promise.all([ApiClient.getGovernmentDashboard(),ApiClient.getGovernmentDestinations()]);if(dashboard.success&&dashboard.data){setStats(dashboard.data.stats);setInsights(dashboard.data.insights||[]);}else setError(dashboard.message||'Data tidak dapat dimuat.');if(destinations.success)setPerformance(destinations.data||[]);setLoading(false);};useEffect(()=>{void load();},[]);
 const report=async()=>{const r=await ApiClient.getGovernmentReports();if(!r.success){setError(r.message||'Laporan gagal dibuat.');return;}const url=URL.createObjectURL(new Blob([JSON.stringify(r.data,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download='aktivitas-takono.json';link.click();URL.revokeObjectURL(url);setDownloaded(true);};
 return <main className="workspace"><PageHeading title="Aktivitas Pengguna TAKONO" description="Ringkasan anonim dari interaksi yang tercatat di platform." action={<button className="primary-button" onClick={report}>{downloaded?'Laporan diunduh':'Unduh laporan'}</button>}/>{error&&<Notice error>{error} <button className="underline" onClick={load}>Coba lagi</button></Notice>}{loading?<p className="text-sm text-slate-500">Memuat aktivitas…</p>:<>
 <section className="grid grid-cols-2 lg:grid-cols-3 gap-px bg-slate-200 border border-slate-200 rounded-2xl overflow-hidden">{metrics.map(([label,key])=><div className="bg-white p-4 sm:p-6" key={key}><p className="text-xs text-slate-500">{label}</p><p className="text-2xl font-semibold mt-1">{Number(stats?.[key]||0)}</p></div>)}</section>
 <section className="panel"><h2 className="font-semibold mb-4">Performa destinasi</h2>{!performance.length?<Empty title="Belum ada data"/>:<div className="overflow-x-auto"><table className="w-full text-sm text-left min-w-[680px]"><thead className="text-slate-500"><tr>{['Destinasi','Explore','Kuis','Event','Reward','Usaha lokal'].map(x=><th className="pb-3 pr-5 font-medium" key={x}>{x}</th>)}</tr></thead><tbody>{performance.map(({destination,stats:s})=><tr className="border-t" key={destination.id}><td className="py-4 pr-5 font-medium">{destination.name}</td>{[s.totalExplorePointsDiscovered,s.totalQuizzesCompleted,s.totalEventParticipations,s.totalRewardRedemptions,s.totalLocalDiscoveryVisits].map((n,i)=><td className="py-4 pr-5" key={i}>{n||0}</td>)}</tr>)}</tbody></table></div>}</section>
 <div className="grid lg:grid-cols-2 gap-6"><section className="panel"><h2 className="font-semibold mb-4">Tren 7 hari</h2><div className="divide-y">{stats?.activityTrendsByDay.map(day=><div className="py-3 flex justify-between text-sm" key={day.date}><span>{new Date(day.date+'T00:00:00').toLocaleDateString('id-ID',{weekday:'short',day:'numeric',month:'short'})}</span><b>{day.count}</b></div>)}</div></section><section className="panel"><h2 className="font-semibold mb-4">Insight</h2>{!insights.length?<Empty title="Belum ada data" description="Insight muncul setelah aktivitas tercatat."/>:<div className="space-y-4">{insights.map(x=><article key={x.id}><h3 className="font-medium">{x.title}</h3><p className="text-sm text-slate-600 mt-1">{x.finding}</p><p className="text-sm text-blue-800 mt-2">{x.recommendation}</p></article>)}</div>}</section></div>
 <section className="panel"><h2 className="font-semibold">Transparansi data</h2><p className="text-sm text-slate-600 mt-2 max-w-3xl">Data hanya berasal dari aktivitas di TAKONO: scan Explore Point, kuis, event, reward, dan Local Discovery. Angka ini bukan jumlah pengunjung fisik dan tidak menampilkan identitas traveler.</p></section></>}</main>;
}
