import React, {useEffect,useState} from 'react';
import {ApiClient} from '../../lib/api';
import {ContentEditor} from '../../components/ContentEditor';
import {useAuth} from '../../context/AuthContext';
import {QRCode} from '../../components/QRCode';
import {Empty,Notice,PageHeading} from '../../components/Workspace';
import {statusLabels} from '../../lib/content';
const tabs:Record<string,string>={destination:'Profil destinasi','explore-points':'Explore Points',events:'Event',rewards:'Reward','local-discoveries':'Local Discovery'};
export function ManagerDashboard({onNavigate}:{onNavigate:(p:string)=>void}) {
 const {user}=useAuth();const [kind,setKind]=useState('destination');const [data,setData]=useState<any[]>([]);const [dashboard,setDashboard]=useState<any>(null);
 const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');const [editor,setEditor]=useState<any>(undefined);
 const [destinations,setDestinations]=useState<any[]>([]);const [selected,setSelected]=useState(user?.destinationId||'');
 const suffix=user?.role==='super_admin'?'?destinationId='+encodeURIComponent(selected):'';
 const load=async()=>{if(user?.role==='super_admin'&&!selected){setLoading(false);return;}setLoading(true);setError('');const [a,b]=await Promise.all([ApiClient.request<any>('/manager/dashboard'+suffix),ApiClient.request<any>('/manager/'+kind+suffix)]);if(a.success)setDashboard(a.data);if(b.success){setData(kind==='destination'?[b.data]:b.data||[]);setError('');}else {setError(b.message||'Gagal memuat.');setData([]);}setLoading(false);};
 useEffect(()=>{if(user?.role==='super_admin')ApiClient.request<any>('/admin/dashboard').then(r=>{setDestinations(r.data?.destinations||[]);if(!selected)setSelected(r.data?.destinations?.[0]?.id||'');});},[]);
 useEffect(()=>{void load();},[kind,selected]);
 return <main className="workspace"><PageHeading title="Konten destinasi" description={dashboard?.destination?.name||'Kelola informasi yang tampil untuk traveler.'} action={user?.role==='super_admin'?<select aria-label="Destinasi" className="field" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Pilih destinasi</option>{destinations.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select>:undefined}/>
 <div className="grid grid-cols-2 md:grid-cols-5 gap-3">{[['QR dipindai','totalExplorePointsDiscovered'],['Kuis selesai','totalQuizzesCompleted'],['Event diikuti','totalEventParticipations'],['Reward ditukar','totalRewardRedemptions'],['Usaha dikunjungi','totalLocalDiscoveryVisits']].map(([label,key])=><div className="bg-white p-4 rounded-2xl border border-slate-200" key={key}><span className="text-xs text-slate-500">{label}</span><p className="text-2xl font-semibold">{dashboard?.stats?.[key]??0}</p></div>)}</div>
 <nav className="flex gap-2 overflow-x-auto pb-1">{Object.entries(tabs).map(([key,label])=><button key={key} onClick={()=>setKind(key)} className={'px-4 py-2.5 rounded-xl whitespace-nowrap text-sm '+(kind===key?'bg-slate-900 text-white':'bg-white border border-slate-200')}>{label}</button>)}</nav>
 {message&&<Notice>{message}</Notice>}{error&&<Notice error>{error} {error.includes('belum ditugaskan')&&user?.role!=='super_admin'?<span>Hubungi Admin untuk memilih destinasi akun ini.</span>:<button className="underline" onClick={load}>Coba lagi</button>}</Notice>}
 <section className="panel space-y-4"><div className="flex justify-between items-center"><h2 className="font-semibold">{tabs[kind]}</h2>{kind!=='destination'&&<button disabled={loading||!dashboard?.destination} onClick={()=>setEditor({latitude:dashboard?.destination?.latitude||0,longitude:dashboard?.destination?.longitude||0,estimatedDuration:'15 menit',pointsReward:0})} className="primary-button py-2">Tambah</button>}</div>
 {loading?<p className="text-sm text-slate-500">Memuat konten…</p>:!data.length?<Empty title="Belum ada konten" description="Gunakan tombol Tambah untuk membuat konten pertama."/>:data.map(item=><article key={item.id} className="border-t py-4 space-y-2"><div className="flex flex-col sm:flex-row sm:justify-between gap-3"><div><h3 className="font-semibold">{item.name||item.title}</h3><p className="text-xs text-slate-500">{statusLabels[item.status]||item.status} {kind==='rewards'?' · '+item.claimedCount+' / '+item.quota+' ditukar':''}</p></div><div className="flex gap-2"><button onClick={()=>setEditor(item)} className="secondary-button py-2">Edit</button>{kind!=='destination'&&<button disabled={busy} className="px-3 py-2 text-sm text-rose-700" onClick={async()=>{if(!confirm('Hapus konten ini? Riwayat aktivitas tetap tersimpan.'))return;setBusy(true);const r=await ApiClient.request('/manager/'+kind+'/'+item.id+suffix,{method:'DELETE'});setBusy(false);if(r.success){setMessage('Konten dihapus.');load();}else setError(r.message||'Gagal menghapus.');}}>Hapus</button>}</div></div><p className="text-sm text-slate-600 line-clamp-3">{item.description}</p>
 {kind==='destination'&&<QRCode value={location.origin+location.pathname+'#/scan/'+item.code} label={item.name}/>}
 {kind==='explore-points'&&<div className="text-xs space-y-2"><QRCode value={location.origin+location.pathname+"#/app/scan/"+item.secureToken} label={item.name}/><p>Link QR untuk papan titik:</p><a className="text-blue-600 break-all" href={location.origin+location.pathname+'#/app/scan/'+item.secureToken}>{location.origin+location.pathname+'#/app/scan/'+item.secureToken}</a><p className="text-slate-500">Kuis: {item.quiz?.title||'Belum dibuat'}</p></div>}
 {kind==='events'&&item.qrToken&&<div className="text-xs space-y-2"><QRCode value={location.origin+location.pathname+"#/app/scan/event/"+item.qrToken} label={item.title}/><p className="text-slate-500">Pasang QR ini di lokasi Event. Partisipasi hanya tercatat satu kali per akun.</p></div>}
 </article>)}</section>
 {editor!==undefined&&<ContentEditor key={kind+(editor.id||'new')} kind={kind} record={editor} onClose={()=>setEditor(undefined)} onSave={async payload=>{const endpoint='/manager/'+kind+(kind!=='destination'&&editor.id?'/'+editor.id:'')+suffix;const r=await ApiClient.request(endpoint,{method:kind==='destination'||editor.id?'PUT':'POST',body:JSON.stringify(payload)});if(r.success){setEditor(undefined);setMessage('Perubahan tersimpan.');await load();}return r;}}/>}
 </main>;
}
