import React, {useEffect,useState} from 'react';
import {ApiClient} from '../../lib/api';
import {ContentEditor} from '../../components/ContentEditor';
import {Building2} from 'lucide-react';
import {useAuth} from '../../context/AuthContext';
import {QRCode} from '../../components/QRCode';
const tabs:Record<string,string>={destination:'Profil destinasi','explore-points':'Explore Points',events:'Event',rewards:'Reward','local-discoveries':'Local Discovery'};
export function ManagerDashboard({onNavigate}:{onNavigate:(p:string)=>void}) {
 const {user}=useAuth();const [kind,setKind]=useState('destination');const [data,setData]=useState<any[]>([]);const [dashboard,setDashboard]=useState<any>(null);
 const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');const [editor,setEditor]=useState<any>(undefined);
 const [destinations,setDestinations]=useState<any[]>([]);const [selected,setSelected]=useState(user?.destinationId||'');
 const suffix=user?.role==='super_admin'?'?destinationId='+encodeURIComponent(selected):'';
 const load=async()=>{setLoading(true);setError('');const [a,b]=await Promise.all([ApiClient.request<any>('/manager/dashboard'+suffix),ApiClient.request<any>('/manager/'+kind+suffix)]);if(a.success)setDashboard(a.data);if(b.success)setData(kind==='destination'?[b.data]:b.data||[]);else {setError(b.message||'Gagal memuat.');setData([]);}setLoading(false);};
 useEffect(()=>{if(user?.role==='super_admin')ApiClient.request<any>('/admin/dashboard').then(r=>{setDestinations(r.data?.destinations||[]);if(!selected)setSelected(r.data?.destinations?.[0]?.id||'');});},[]);
 useEffect(()=>{load();},[kind,selected]);
 return <main className="min-h-screen bg-slate-100 py-8"><div className="max-w-7xl mx-auto px-4 space-y-6">
 <header className="bg-white p-6 rounded-3xl border border-slate-200 flex flex-wrap justify-between gap-4"><div><h1 className="text-xl font-extrabold flex items-center gap-2"><Building2/>Portal Pengelola Destinasi</h1><p className="text-sm text-slate-500">{dashboard?.destination?.name} · {user?.name}</p></div>{user?.role==='super_admin'&&<select aria-label="Destinasi" className="border p-2 rounded-xl" value={selected} onChange={e=>setSelected(e.target.value)}>{destinations.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select>}</header>
 <p className="text-xs text-slate-600">Aktivitas Pengguna TAKONO — data interaksi aplikasi, bukan jumlah pengunjung fisik.</p>
 <div className="grid grid-cols-2 md:grid-cols-5 gap-3">{[['Explore Point','totalExplorePointsDiscovered'],['Kuis','totalQuizzesCompleted'],['Event','totalEventParticipations'],['Reward','totalRewardRedemptions'],['Local Discovery','totalLocalDiscoveryVisits']].map(([label,key])=><div className="bg-white p-4 rounded-2xl border" key={key}><span className="text-xs text-slate-500">{label}</span><p className="text-2xl font-bold">{dashboard?.stats?.[key]??0}</p></div>)}</div>
 <nav className="flex gap-2 overflow-x-auto">{Object.entries(tabs).map(([key,label])=><button key={key} onClick={()=>setKind(key)} className={'px-4 py-3 rounded-xl whitespace-nowrap text-sm '+(kind===key?'bg-blue-600 text-white':'bg-white border')}>{label}</button>)}</nav>
 {message&&<p role="status" className="text-emerald-700">{message}</p>}{error&&<p role="alert" className="text-rose-700">{error} <button onClick={load}>Coba lagi</button></p>}
 <section className="bg-white rounded-3xl border p-6 space-y-4"><div className="flex justify-between items-center"><h2 className="font-bold">{tabs[kind]}</h2>{kind!=='destination'&&<button disabled={loading} onClick={()=>setEditor({latitude:dashboard?.destination?.latitude||0,longitude:dashboard?.destination?.longitude||0,estimatedDuration:'15 menit',pointsReward:10})} className="bg-blue-600 text-white px-4 py-2 rounded-xl">+ Tambah</button>}</div>
 {loading?<p>Memuat…</p>:!data.length?<p className="text-slate-500">Belum ada konten.</p>:data.map(item=><article key={item.id} className="border-t py-4 space-y-2"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-semibold">{item.name||item.title}</h3><p className="text-xs text-slate-500">{item.status} {kind==='rewards'?' · '+item.claimedCount+' / '+item.quota+' ditukar':''}</p></div><div className="flex gap-2"><button onClick={()=>setEditor(item)} className="bg-blue-50 text-blue-700 rounded-lg px-3 py-2">Edit</button>{kind!=='destination'&&<button disabled={busy} className="bg-rose-50 text-rose-700 rounded-lg px-3 py-2" onClick={async()=>{if(!confirm('Hapus konten ini? Riwayat aktivitas tetap tersimpan.'))return;setBusy(true);const r=await ApiClient.request('/manager/'+kind+'/'+item.id+suffix,{method:'DELETE'});setBusy(false);if(r.success){setMessage('Konten dihapus.');load();}else setError(r.message||'Gagal menghapus.');}}>Hapus</button>}</div></div><p className="text-sm text-slate-600">{item.description}</p>
 {kind==='destination'&&<QRCode value={location.origin+location.pathname+'#/scan/'+item.code} label={item.name}/>}
 {kind==='explore-points'&&<div className="text-xs space-y-2"><QRCode value={location.origin+location.pathname+"#/app/scan/"+item.secureToken} label={item.name}/><p>Link QR untuk papan titik:</p><a className="text-blue-600 break-all" href={location.origin+location.pathname+'#/app/scan/'+item.secureToken}>{location.origin+location.pathname+'#/app/scan/'+item.secureToken}</a><p className="text-slate-500">Kuis: {item.quiz?.title||'Belum dibuat'}</p></div>}
 </article>)}</section>
 {editor!==undefined&&<ContentEditor key={kind+(editor.id||'new')} kind={kind} record={editor} onClose={()=>setEditor(undefined)} onSave={async payload=>{const endpoint='/manager/'+kind+(kind!=='destination'&&editor.id?'/'+editor.id:'')+suffix;const r=await ApiClient.request(endpoint,{method:kind==='destination'||editor.id?'PUT':'POST',body:JSON.stringify(payload)});if(r.success){setEditor(undefined);setMessage('Perubahan tersimpan.');await load();}return r;}}/>}
 </div></main>;
}
