import React,{useEffect,useState} from 'react';
import {ArrowRight,Calendar,Gift,MapPin,QrCode} from 'lucide-react';
import {ApiClient} from '../../lib/api';
import {Destination,DestinationEvent,ExplorePoint,LocalDiscovery,Reward} from '../../types';
import {useAuth} from '../../context/AuthContext';
export function TravelerHome({onNavigate,onOpenScanModal}:{onNavigate:(p:string)=>void;onOpenScanModal:()=>void}) {
 const {user,pointsBalance}=useAuth();const [destination,setDestination]=useState<Destination|null>(null),[next,setNext]=useState<ExplorePoint|null>(null),[progress,setProgress]=useState<any>(),[events,setEvents]=useState<DestinationEvent[]>([]),[local,setLocal]=useState<LocalDiscovery[]>([]),[rewards,setRewards]=useState<Reward[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{(async()=>{setLoading(true);const [d,r,e,w]=await Promise.all([ApiClient.getDestinationBySlug(),ApiClient.getSmartGuideRecommendations(),ApiClient.getEvents(),ApiClient.getRewards()]);if(d.success&&d.data){setDestination(d.data.destination);setLocal(d.data.localDiscoveries||[]);}else setError(d.message||'Destinasi tidak dapat dimuat.');if(r.success&&r.data){setNext(r.data.nextRecommendation.point);setProgress(r.data.progress);}if(e.success)setEvents(e.data||[]);if(w.success)setRewards(w.data||[]);setLoading(false);})();},[]);
 if(loading)return <div className="py-16 text-center text-sm text-slate-500">Menyiapkan perjalanan…</div>;
 if(error)return <div className="py-12"><p role="alert" className="text-sm text-rose-700">{error}</p><button className="mt-4 text-blue-700" onClick={()=>onNavigate('/destinations')}>Pilih destinasi</button></div>;
 return <div className="space-y-8 pb-8"><header><p className="text-sm text-slate-500">Halo, {user?.name.split(' ')[0]}</p><div className="flex items-start justify-between gap-4 mt-1"><div><h1 className="text-2xl font-semibold tracking-tight">{destination?.name}</h1><p className="text-sm text-slate-500 flex items-center gap-1 mt-1"><MapPin size={14}/>{destination?.city}</p></div><button onClick={()=>onNavigate('/app/profile')} className="text-right"><b className="block text-xl">{pointsBalance}</b><span className="text-xs text-slate-500">poin</span></button></div></header>
 <section className="relative overflow-hidden rounded-2xl min-h-72"><img src={destination?.heroImage} alt={destination?.name} className="absolute inset-0 w-full h-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-slate-950/90 via-slate-950/15 to-transparent"/><div className="relative min-h-72 p-5 flex flex-col justify-end text-white"><p className="text-xs text-white/75">REKOMENDASI BERIKUTNYA</p><h2 className="text-xl font-semibold mt-1">{next?.name||'Semua titik sudah dijelajahi'}</h2><p className="text-sm text-white/80 mt-1 line-clamp-2">{next?.description||'Lihat album perjalananmu atau temukan aktivitas lain.'}</p><div className="flex gap-2 mt-5">{next&&<button className="bg-white text-slate-950 px-4 py-2.5 rounded-xl text-sm font-medium" onClick={()=>onNavigate('/app/smart-guide')}>Lihat rute</button>}<button className="bg-slate-950/70 border border-white/30 px-4 py-2.5 rounded-xl text-sm" onClick={onOpenScanModal}><QrCode size={16} className="inline mr-2"/>Scan QR</button></div></div></section>
 <section><div className="flex justify-between items-end"><div><h2 className="font-semibold">Perjalananmu</h2><p className="text-sm text-slate-500 mt-1">{progress?.completedExplorePoints||0} dari {progress?.totalExplorePoints||0} titik selesai</p></div><button className="text-sm text-blue-700" onClick={()=>onNavigate('/app/album')}>Lihat album</button></div><div className="h-2 bg-slate-200 mt-4"><div className="h-full bg-blue-600" style={{width:`${progress?.totalExplorePoints?100*progress.completedExplorePoints/progress.totalExplorePoints:0}%`}}/></div></section>
 <section><div className="flex justify-between items-center mb-4"><h2 className="font-semibold">Sedang berlangsung</h2><button className="text-sm text-blue-700" onClick={()=>onNavigate('/app/events')}>Semua event</button></div>{events.length?<div className="divide-y border-y border-slate-200">{events.slice(0,2).map(e=><button key={e.id} onClick={()=>onNavigate('/app/events')} className="w-full py-4 flex text-left gap-4"><Calendar className="text-blue-600 shrink-0" size={20}/><span className="flex-1"><b className="block text-sm">{e.title}</b><span className="text-xs text-slate-500">{e.startDate} · {e.time}</span></span><ArrowRight size={17}/></button>)}</div>:<p className="text-sm text-slate-500">Belum ada event.</p>}</section>
 <section className="grid grid-cols-2 gap-3"><button onClick={()=>onNavigate('/app/local-discovery')} className="text-left border-t-2 border-slate-900 pt-4"><span className="text-2xl font-semibold">{local.length}</span><b className="block text-sm mt-2">Usaha lokal</b><span className="text-xs text-slate-500">Kuliner dan produk sekitar</span></button><button onClick={()=>onNavigate('/app/rewards')} className="text-left border-t-2 border-blue-600 pt-4"><span className="text-2xl font-semibold">{rewards.length}</span><b className="block text-sm mt-2">Reward tersedia</b><span className="text-xs text-slate-500"><Gift size={13} className="inline mr-1"/>Gunakan poinmu</span></button></section>
 </div>;
}
