import React from 'react';
import {TakonoLogo} from './TakonoLogo';
import {useAuth} from '../context/AuthContext';
import {ApiClient} from '../lib/api';
import {roleLabels} from '../lib/content';
export function Workspace({children,onNavigate}:{children:React.ReactNode;onNavigate:(p:string)=>void}) {
 const {user,logout,refreshUserData}=useAuth();const [error,setError]=React.useState(''),[busy,setBusy]=React.useState(false),[settings,setSettings]=React.useState(false);
 return <div className="min-h-screen bg-slate-50"><header className="border-b border-slate-200 bg-white"><div className="max-w-6xl mx-auto px-4 sm:px-6 h-16 flex items-center justify-between gap-3"><button onClick={()=>onNavigate('/')} aria-label="Beranda TAKONO"><TakonoLogo size="sm"/></button><div className="flex items-center gap-3"><button onClick={()=>setSettings(true)} className="text-sm text-slate-600"><span className="hidden sm:inline">{user?.name}</span><span className="sm:hidden">Akun</span></button><span className="text-xs text-blue-700 rounded-lg bg-blue-50 px-2 py-1">{roleLabels[user?.role||'']}</span><button disabled={busy} className="text-sm py-3 disabled:opacity-50" onClick={async()=>{setBusy(true);const r=await logout();setBusy(false);if(r.success)onNavigate('/login');else setError(r.message||'Gagal keluar.');}}>Keluar</button></div></div></header>{user?.role==='super_admin'&&<nav className="max-w-6xl mx-auto flex gap-2 px-4 sm:px-6 pt-4 overflow-x-auto" aria-label="Portal admin">{[['/admin','Pengguna'],['/manager','Konten'],['/government','Aktivitas']].map(([path,label])=><button key={path} onClick={()=>onNavigate(path)} className={'px-4 py-2 rounded-lg text-sm '+(location.hash==='#'+path?'bg-slate-900 text-white':'bg-white border border-slate-200')}>{label}</button>)}</nav>}{error&&<div className="workspace"><Notice error>{error}</Notice></div>}{children}
 {settings&&<div className="fixed inset-0 z-50 bg-slate-950/50 p-4 flex items-center justify-center"><section role="dialog" aria-modal="true" aria-label="Pengaturan akun" className="bg-white rounded-2xl w-full max-w-md p-6"><h2 className="text-lg font-semibold">Pengaturan akun</h2><p className="text-sm text-slate-500 mt-1">{user?.email}</p><form className="mt-5 space-y-4" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);const r=await ApiClient.updateProfile({name:String(f.get('name')),currentPassword:String(f.get('currentPassword')),password:String(f.get('password')),passwordConfirmation:String(f.get('passwordConfirmation'))});setBusy(false);if(r.success){await refreshUserData();setSettings(false);}else setError(r.message||'Gagal menyimpan.');}}><label className="block text-sm font-medium">Nama<input className="field mt-1" name="name" defaultValue={user?.name} required/></label><div className="border-t pt-4"><p className="text-sm font-medium">Ganti password <span className="font-normal text-slate-400">(opsional)</span></p><label className="block text-sm mt-3">Password saat ini<input className="field mt-1" type="password" name="currentPassword" autoComplete="current-password"/></label><label className="block text-sm mt-3">Password baru<input className="field mt-1" type="password" name="password" minLength={10} autoComplete="new-password"/></label><label className="block text-sm mt-3">Ulangi password baru<input className="field mt-1" type="password" name="passwordConfirmation" minLength={10} autoComplete="new-password"/></label></div>{error&&<Notice error>{error}</Notice>}<div className="flex gap-3"><button type="button" className="secondary-button flex-1" onClick={()=>setSettings(false)}>Batal</button><button disabled={busy} className="primary-button flex-1">{busy?'Menyimpan…':'Simpan'}</button></div></form></section></div>}
 </div>;
}
export function PageHeading({title,description,action}:{title:string;description?:string;action?:React.ReactNode}) {return <header className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><h1 className="text-2xl font-semibold tracking-tight">{title}</h1>{description&&<p className="text-sm text-slate-500 mt-1">{description}</p>}</div>{action}</header>;}
export function Notice({children,error=false}:{children:React.ReactNode;error?:boolean}) {return <div role={error?'alert':'status'} className={'rounded-xl p-4 text-sm '+(error?'bg-rose-50 text-rose-800':'bg-blue-50 text-blue-900')}>{children}</div>;}
export function Empty({title,description}:{title:string;description?:string}) {return <div className="py-10 text-center"><p className="font-medium text-slate-700">{title}</p>{description&&<p className="text-sm text-slate-500 mt-2">{description}</p>}</div>;}
