import React from 'react';
import {ArrowRight,Compass,MapPin,QrCode} from 'lucide-react';
import {Destination,ExplorePoint,LocalDiscovery} from '../../types';
import heroFallback from '../../assets/images/hero_takono_tourism_1790168118274.jpg';
export function HomePage({destination,explorePoints=[],localDiscoveries,onNavigate,onOpenScanModal}:{destination:Destination|null;explorePoints?:ExplorePoint[];localDiscoveries:LocalDiscovery[];onNavigate:(p:string)=>void;onOpenScanModal:()=>void}) {
 const image=destination?.heroImage||heroFallback;
 return <main className="bg-white"><section className="max-w-7xl mx-auto px-4 sm:px-6 py-8 sm:py-14"><div className="grid lg:grid-cols-2 gap-8 lg:gap-14 items-center"><div><p className="text-sm font-semibold text-blue-700 mb-4">Panduan wisata dalam satu aplikasi</p><h1 className="text-4xl sm:text-5xl font-semibold tracking-tight leading-tight">Kenali tempatnya.<br/>Temukan ceritanya.</h1><p className="mt-5 text-base text-slate-600 leading-relaxed max-w-xl">Buka peta, scan QR di lokasi, baca cerita, lalu kumpulkan poin dari perjalananmu.</p><div className="mt-7 flex flex-col sm:flex-row gap-3"><button className="primary-button" onClick={()=>onNavigate('/app')}><Compass size={18}/>Mulai jelajah</button><button className="secondary-button" onClick={onOpenScanModal}><QrCode size={18}/>Scan QR</button></div></div><img src={image} alt={destination?.name||'Destinasi TAKONO'} className="w-full h-72 sm:h-96 object-cover rounded-2xl"/></div></section>
 <section className="bg-slate-50 border-y border-slate-200"><div className="max-w-7xl mx-auto px-4 sm:px-6 py-10"><div className="grid sm:grid-cols-3 gap-8"><div><b className="text-2xl">{explorePoints.length}</b><p className="text-sm text-slate-500 mt-1">Titik jelajah tersedia</p></div><div><b className="text-2xl">{localDiscoveries.length}</b><p className="text-sm text-slate-500 mt-1">Usaha lokal terhubung</p></div><div><b className="text-2xl">{explorePoints.reduce((n,p)=>n+p.pointsReward,0)}</b><p className="text-sm text-slate-500 mt-1">Poin dari Explore Point</p></div></div></div></section>
 <section className="max-w-7xl mx-auto px-4 sm:px-6 py-12"><div className="flex flex-col sm:flex-row sm:items-end justify-between gap-4 mb-6"><div><p className="text-sm text-blue-700 font-medium">Destinasi aktif</p><h2 className="text-2xl font-semibold mt-1">{destination?.name||'Belum ada destinasi'}</h2></div>{destination&&<button className="text-sm text-blue-700 font-medium" onClick={()=>onNavigate('/destinations/'+destination.slug)}>Lihat detail →</button>}</div>{destination?<div className="grid md:grid-cols-[1.5fr_1fr] border border-slate-200 rounded-2xl overflow-hidden"><img src={destination.gallery?.[0]||image} alt="" className="w-full h-64 object-cover"/><div className="p-6 flex flex-col justify-between"><div><p className="text-sm text-slate-600 leading-relaxed line-clamp-5">{destination.description}</p><p className="flex items-start gap-2 text-sm text-slate-500 mt-5"><MapPin size={17} className="shrink-0"/>{destination.address}</p></div><button className="primary-button mt-6" onClick={()=>onNavigate('/app/smart-guide')}>Buka Smart Guide <ArrowRight size={17}/></button></div></div>:<p className="text-slate-500">Belum ada data</p>}</section>
 <section className="max-w-7xl mx-auto px-4 sm:px-6 pb-14"><h2 className="text-2xl font-semibold">Cara menggunakan TAKONO</h2><ol className="grid md:grid-cols-3 gap-6 mt-6">{[['01','Pilih destinasi','Lihat informasi dan titik yang tersedia.'],['02','Scan di lokasi','Scan QR pada papan Explore Point.'],['03','Selesaikan perjalanan','Baca cerita, jawab kuis, dan gunakan poin.']].map(([n,title,text])=><li key={n} className="border-t-2 border-slate-900 pt-4"><span className="text-xs text-slate-400">{n}</span><h3 className="font-semibold mt-2">{title}</h3><p className="text-sm text-slate-600 mt-1">{text}</p></li>)}</ol></section></main>;
}
