import React, { useEffect, useState } from 'react';
import { Search, Plus, Users, MapPin, Activity, ArrowUpRight, ShieldCheck } from 'lucide-react';
import { ApiClient } from '../../lib/api';
import { ContentEditor } from '../../components/ContentEditor';
import { Empty, Notice, PageHeading } from '../../components/Workspace';
import { roleLabels, statusLabels } from '../../lib/content';

export function AdminDashboard({ onNavigate }: { onNavigate: (path: string) => void }) {
  const [data, setData] = useState<any>(null), [error, setError] = useState(''), [message, setMessage] = useState('');
  const [editor, setEditor] = useState<any>(), [kind, setKind] = useState('users'), [loading, setLoading] = useState(true);
  const [query, setQuery] = useState(''), [role, setRole] = useState('all'), [tab, setTab] = useState('users');
  const load = async () => { setLoading(true); setError(''); const r = await ApiClient.request<any>('/admin/dashboard'); if (r.success) setData(r.data); else setError(r.message || 'Data admin tidak dapat dimuat.'); setLoading(false); };
  useEffect(() => { void load(); }, []);
  const edit = (record: any) => { setKind('users'); setEditor(record); setMessage(''); };
  const users = (data?.users || []).filter((u: any) => (role === 'all' || u.role === role) && `${u.name} ${u.email}`.toLowerCase().includes(query.toLowerCase()));
  return <main className="workspace admin-shell">
    <div className="portal-intro"><p className="portal-eyebrow">ADMINISTRASI TAKONO</p><PageHeading title="Kelola akses. Hubungkan destinasi." description="Atur akun dan penugasan agar setiap tim bisa bekerja dengan tepat." action={<button className="primary-button" onClick={() => edit({ role: 'traveler', active: true })}><Plus size={17} />Tambah pengguna</button>} /></div>
    {message && <Notice>{message}</Notice>}{error && <Notice error>{error} <button className="underline" onClick={load}>Coba lagi</button></Notice>}
    {loading ? <p className="text-sm text-slate-500">Memuat pengguna…</p> : data && <>
      <section className="portal-totals">{[[Users, data.users.length, 'Pengguna'], [MapPin, data.destinations.length, 'Destinasi'], [Activity, data.activityCount, 'Aktivitas tercatat']].map(([Icon, count, label]: any) => <div key={label}><Icon size={19} strokeWidth={1.5} /><strong>{count}</strong><span>{label}</span></div>)}</section>
      <nav aria-label="Manajemen platform" className="portal-tabs">{[['users', 'Pengguna'], ['destinations', 'Destinasi'], ['logs', 'Riwayat perubahan']].map(([key, label]) => <button key={key} aria-current={tab === key ? 'page' : undefined} onClick={() => setTab(key)}>{label}</button>)}</nav>
      {tab === 'users' && <section className="panel !p-0 overflow-hidden">
        <div className="flex flex-col justify-between gap-4 border-b border-slate-100 p-5 sm:flex-row sm:items-center"><div><h2 className="text-base font-semibold">Pengguna platform</h2><p className="mt-1 text-xs text-slate-500">{users.length} akun sesuai filter</p></div><div className="flex flex-wrap gap-2"><label className="relative min-w-0 flex-1"><span className="sr-only">Cari pengguna</span><Search size={16} className="absolute left-3 top-3.5 text-slate-400" /><input className="field !pl-9" placeholder="Cari nama atau email" value={query} onChange={e => setQuery(e.target.value)} /></label><select aria-label="Filter peran" className="field !w-auto" value={role} onChange={e => setRole(e.target.value)}><option value="all">Semua peran</option>{Object.entries(roleLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></div></div>
        <div className="hidden grid-cols-[1.4fr_1fr_1fr_auto] gap-4 border-b border-slate-100 bg-slate-50 px-6 py-3 text-xs font-medium text-slate-500 md:grid"><span>Nama & email</span><span>Peran</span><span>Status</span><span>Aksi</span></div>
        {!users.length ? <Empty title="Tidak ada pengguna ditemukan" description="Coba nama lain atau ubah filter peran." /> : <div className="divide-y divide-slate-100">{users.map((u: any) => <article key={u.id} className="flex flex-col gap-3 px-5 py-5 text-sm md:grid md:grid-cols-[1.4fr_1fr_1fr_auto] md:items-center md:gap-4 md:px-6"><div className="min-w-0"><strong className="block font-semibold">{u.name}</strong><span className="mt-1 block break-all text-xs text-slate-500">{u.email}</span></div><div><span>{roleLabels[u.role] || u.role}</span>{u.role === 'destination_manager' && <p className="mt-1 text-xs text-slate-500">{data.destinations.find((d: any) => d.id === u.destinationId)?.name || 'Belum ditugaskan'}</p>}</div><span className={`inline-flex w-fit items-center gap-2 text-xs ${u.active ? 'text-emerald-700' : 'text-slate-500'}`}><span className={`h-1.5 w-1.5 rounded-full ${u.active ? 'bg-emerald-500' : 'bg-slate-400'}`} />{u.active ? 'Aktif' : 'Nonaktif'}</span><button className="secondary-button !py-2" onClick={() => edit(u)}>Edit</button></article>)}</div>}
      </section>}
      {tab === 'destinations' && <section className="panel"><div className="mb-6 flex items-center justify-between gap-3"><h2 className="text-base font-semibold">Destinasi terhubung</h2><button className="secondary-button" onClick={() => { setKind('destination'); setEditor({ status: 'draft' }); }}><Plus size={16} />Tambah</button></div><div className="divide-y divide-slate-100">{data.destinations.map((d: any) => <div key={d.id} className="flex items-center justify-between gap-4 py-4"><div><h3 className="font-medium">{d.name}</h3><p className="mt-1 text-xs text-slate-500">{d.city}</p></div><span className="text-xs text-slate-500">{statusLabels[d.status] || d.status}</span></div>)}</div><button className="mt-5 inline-flex items-center gap-2 text-sm font-medium text-blue-700" onClick={() => onNavigate('/manager')}>Kelola konten destinasi <ArrowUpRight size={16} /></button></section>}
      {tab === 'logs' && <section className="panel"><h2 className="flex items-center gap-2 text-base font-semibold"><ShieldCheck size={19} />Riwayat perubahan</h2><p className="mt-2 text-sm text-slate-500">Perubahan yang tercatat dalam pengelolaan platform.</p><div className="mt-5 divide-y divide-slate-100">{!data.auditLogs.length && <Empty title="Belum ada perubahan" />}{data.auditLogs.map((a: any) => <div key={a.id} className="grid gap-2 py-4 text-sm sm:grid-cols-[180px_1fr]"><time className="text-xs text-slate-500">{new Date(a.createdAt).toLocaleString('id-ID')}</time><p className="break-words">{a.action} {a.resource}</p></div>)}</div></section>}
    </>}
    {editor !== undefined && <ContentEditor kind={kind} record={editor} destinations={data?.destinations || []} onClose={() => setEditor(undefined)} onSave={async payload => { const path = kind === 'destination' ? '/admin/destinations' : '/admin/users' + (editor.id ? '/' + editor.id : ''); const r = await ApiClient.request(path, { method: editor.id ? 'PUT' : 'POST', body: JSON.stringify(payload) }); if (r.success) { setEditor(undefined); setMessage('Perubahan tersimpan.'); await load(); } return r; }} />}
  </main>;
}
