import React,{useEffect,useState} from 'react';
import {ApiClient} from '../../lib/api';
import {ContentEditor} from '../../components/ContentEditor';
import {Empty,Notice,PageHeading} from '../../components/Workspace';
import {roleLabels,statusLabels} from '../../lib/content';
export function AdminDashboard({onNavigate}:{onNavigate:(path:string)=>void}) {
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[message,setMessage]=useState('');const [editor,setEditor]=useState<any>(),[kind,setKind]=useState('users'),[loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);setError('');const r=await ApiClient.request<any>('/admin/dashboard');if(r.success)setData(r.data);else setError(r.message||'Data admin tidak dapat dimuat.');setLoading(false);};useEffect(()=>{void load();},[]);
 const edit=(record:any)=>{setKind('users');setEditor(record);setMessage('');};
 return <main className="workspace"><PageHeading title="Administrasi" description="Akun, peran, dan penugasan destinasi." action={<button className="primary-button" onClick={()=>edit({role:'traveler',active:true})}>Tambah pengguna</button>}/>
 {message&&<Notice>{message}</Notice>}{error&&<Notice error>{error} <button className="underline" onClick={load}>Coba lagi</button></Notice>}
 {loading?<p className="text-sm text-slate-500">Memuat pengguna…</p>:data&&<><section className="panel"><div className="flex flex-wrap gap-x-8 gap-y-2 text-sm"><span><b>{data.users.length}</b> pengguna</span><span><b>{data.destinations.length}</b> destinasi</span><span><b>{data.activityCount}</b> aktivitas</span></div></section>
 <section className="panel p-0 sm:p-0 overflow-hidden"><div className="p-4 sm:p-6 border-b"><h2 className="font-semibold">Pengguna</h2></div>{!data.users.length?<Empty title="Belum ada pengguna"/>:<div className="divide-y">{data.users.map((u:any)=><article key={u.id} className="p-4 sm:px-6 flex flex-col md:grid md:grid-cols-[1.2fr_1.4fr_1fr_1fr_auto] gap-2 md:items-center text-sm"><div><b className="block">{u.name}</b><span className="text-slate-500 md:hidden">{u.email}</span></div><span className="hidden md:block text-slate-600 break-all">{u.email}</span><span>{roleLabels[u.role]||u.role}</span><span className={u.active?'text-emerald-700':'text-slate-400'}>{u.active?'Aktif':'Nonaktif'}</span><button className="secondary-button py-2" onClick={()=>edit(u)}>Edit</button>{u.role==='destination_manager'&&<p className="md:col-start-3 md:col-span-3 text-xs text-slate-500">Destinasi: {data.destinations.find((d:any)=>d.id===u.destinationId)?.name||'Belum ditugaskan'}</p>}</article>)}</div>}</section>
 <section className="panel"><div className="flex items-center justify-between gap-3 mb-4"><h2 className="font-semibold">Destinasi</h2><button className="secondary-button py-2" onClick={()=>{setKind('destination');setEditor({status:'draft'});}}>Tambah</button></div><div className="divide-y">{data.destinations.map((d:any)=><div key={d.id} className="py-3 flex justify-between gap-3 text-sm"><span>{d.name}</span><span className="text-slate-500">{statusLabels[d.status]||d.status}</span></div>)}</div><button className="mt-4 text-sm text-blue-700" onClick={()=>onNavigate('/manager')}>Kelola konten destinasi →</button></section>
 <details className="panel"><summary className="font-semibold cursor-pointer">Riwayat perubahan ({data.auditLogs.length})</summary><div className="divide-y mt-4">{!data.auditLogs.length&&<Empty title="Belum ada perubahan"/>}{data.auditLogs.map((a:any)=><p key={a.id} className="py-3 text-xs text-slate-600">{new Date(a.createdAt).toLocaleString('id-ID')} · {a.action} {a.resource}</p>)}</div></details></>}
 {editor!==undefined&&<ContentEditor kind={kind} record={editor} destinations={data?.destinations||[]} onClose={()=>setEditor(undefined)} onSave={async payload=>{const path=kind==='destination'?'/admin/destinations':'/admin/users'+(editor.id?'/'+editor.id:'');const r=await ApiClient.request(path,{method:editor.id?'PUT':'POST',body:JSON.stringify(payload)});if(r.success){setEditor(undefined);setMessage('Perubahan tersimpan.');await load();}return r;}}/>}</main>;
}
